### ISSUE TITLE
Unable to find extension point configuration extensions/compiler.xml

### ISSUE THREAD

**Issue by javaXN** [Kotlin/kotlin-script-examples#24]
javax.script.ScriptException: ERROR Unable to initialize repl compiler:
  DEBUG Using JDK home inferred from java.home: D:\2_My_Work_Application\graalvm-ce-java17-22.3.0
  DEBUG Using JVM IR backend
  ERROR Unable to find extension point configuration extensions/compiler.xml (cp:
  null): java.lang.IllegalStateException: Unable to find extension point configuration extensions/compiler.xml (cp:
  null): java.lang.IllegalStateException: Unable to initialize repl compiler:
  DEBUG Using JDK home inferred from java.home: D:\2_My_Work_Application\graalvm-ce-java17-22.3.0
  DEBUG Using JVM IR backend
  ERROR Unable to find extension point configuration extensions/compiler.xml (cp:
  null): java.lang.IllegalStateException: Unable to find extension point configuration extensions/compiler.xml (cp:
  null)
	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.asJsr223EvalResult(KotlinJsr223JvmScriptEngineBase.kt:104)
	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compileAndEval(KotlinJsr223JvmScriptEngineBase.kt:63)
	at kotlin.script.experimental.jvmhost.jsr223.KotlinJsr223ScriptEngineImpl.compileAndEval(KotlinJsr223ScriptEngineImpl.kt:95)
	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.eval(KotlinJsr223JvmScriptEngineBase.kt:31)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262)
	at cn.hutool.script.FullSupportScriptEngine.eval(FullSupportScriptEngine.java:101)
	at com.jnvago.jniot.terminal.resolver.subscribe.second.ScriptCache.set(ScriptCache.kt:77)
	... 34 common frames omitted

**Comment by AmaniAdam0607** [comment]
This have also happened to me, app runs well but when packaged as a jar i get this error, spring boot....any comment?..
